import AppShell from "../../components/shell/AppShell";
import { AiBuilder } from "../../components/ai-builder";
import { BuildsGallery } from "../../components/builds-gallery";
import { Panel, Badge } from "../../components/ui";

export const metadata = { title: "Bauen — Cloud Superbrain" };
export const dynamic = "force-dynamic";

// The build surface: describe an app or game → it is generated by a real code
// model and runs live in the preview → iterate, share, download. Nothing else.
export default function WorkbenchPage() {
  return (
    <AppShell crumb="Bauen" runState="idle">
      <div className="page-wide">
        <Panel title="Bauen mit KI · beschreibe es, es läuft sofort" className="mb-16" actions={<Badge tone="green">echt · live</Badge>}>
          <div className="wb-pad">
            <AiBuilder />
          </div>
        </Panel>

        <Panel title="Zuletzt gebaut" actions={<Badge tone="cyan">Meine Apps</Badge>}>
          <BuildsGallery />
        </Panel>
      </div>
    </AppShell>
  );
}
