from __future__ import annotations

import hashlib
import json
import re
import sys
import urllib.request
from datetime import date
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "services" / "agent-api" / "app" / "openrouter_model_links.py"
OPENROUTER_MODELS_API = "https://openrouter.ai/api/v1/models"
OPENROUTER_MODEL_PAGE_BASE = "https://openrouter.ai/models"
IMPORT_DATE = date.today().isoformat()


def slug(value: str) -> str:
    text = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return text[:90] or "model"


def details_url(model: dict[str, Any]) -> str:
    links = model.get("links") if isinstance(model.get("links"), dict) else {}
    details = str(links.get("details") or "").strip()
    if details.startswith("/"):
        return f"https://openrouter.ai{details}"
    if details.startswith("https://"):
        return details
    canonical_slug = str(model.get("canonical_slug") or model.get("id") or "").strip()
    return f"{OPENROUTER_MODELS_API}/{canonical_slug}/endpoints"


def model_page_url(model: dict[str, Any]) -> str:
    model_id = str(model.get("id") or "").strip()
    return f"{OPENROUTER_MODEL_PAGE_BASE}/{model_id}"


def tags_for_model(model: dict[str, Any]) -> list[str]:
    architecture = model.get("architecture") if isinstance(model.get("architecture"), dict) else {}
    top_provider = model.get("top_provider") if isinstance(model.get("top_provider"), dict) else {}
    tags: list[str] = ["openrouter-api", "model"]
    for field in ["modality", "tokenizer", "instruct_type"]:
        value = architecture.get(field)
        if value:
            tags.append(f"{field}:{value}")
    for modality in architecture.get("input_modalities") or []:
        tags.append(f"input:{modality}")
    for modality in architecture.get("output_modalities") or []:
        tags.append(f"output:{modality}")
    if model.get("hugging_face_id"):
        tags.append(f"hf:{model['hugging_face_id']}")
    if model.get("context_length"):
        tags.append(f"context:{model['context_length']}")
    if top_provider.get("max_completion_tokens"):
        tags.append(f"max_completion:{top_provider['max_completion_tokens']}")
    if top_provider.get("is_moderated") is True:
        tags.append("moderated")
    if str(model.get("id") or "").endswith(":free"):
        tags.append("free")
    return sorted(set(str(tag) for tag in tags))


def normalized_item(model: dict[str, Any]) -> dict[str, Any]:
    model_id = str(model.get("id") or "").strip()
    canonical_slug = str(model.get("canonical_slug") or model_id).strip()
    digest = hashlib.sha1(model_id.encode("utf-8")).hexdigest()[:10]
    architecture = model.get("architecture") if isinstance(model.get("architecture"), dict) else {}
    category = str(architecture.get("modality") or "model_api_entry")
    return {
        "canonical_id": f"openrouter-model-{slug(model_id)}-{digest}",
        "source": "openrouter",
        "kind": "model_entry",
        "name": str(model.get("name") or model_id),
        "url": model_page_url(model),
        "api_url": details_url(model),
        "category": category,
        "tags": tags_for_model(model),
        "license": "source-policy",
        "gated_private": False,
        "dedupe_group": f"openrouter:{model_id}",
        "last_seen": IMPORT_DATE,
        "provider_model_id": model_id,
        "canonical_slug": canonical_slug,
        "context_length": model.get("context_length"),
    }


def fetch_models() -> list[dict[str, Any]]:
    request = urllib.request.Request(
        OPENROUTER_MODELS_API,
        headers={"User-Agent": "cloud-superbrain-link-atlas-importer/1.0"},
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        payload = json.loads(response.read().decode("utf-8"))
    data = payload.get("data")
    if not isinstance(data, list):
        raise RuntimeError("OpenRouter /api/v1/models response did not contain a data list")
    models = [item for item in data if isinstance(item, dict) and item.get("id")]
    if not models:
        raise RuntimeError("OpenRouter /api/v1/models returned no model rows")
    return models


def write_module(items: list[dict[str, Any]]) -> None:
    payload = json.dumps(items, indent=2, sort_keys=True, ensure_ascii=True)
    content = f'''from __future__ import annotations

import json

# Generated by scripts/import_openrouter_models_to_link_atlas.py.
# Source: {OPENROUTER_MODELS_API}
# Imported: {IMPORT_DATE}
# Metadata links only: no model downloads, no provider secrets, no live calls.

OPENROUTER_MODEL_LINK_SOURCE = {{
    "api_url": "{OPENROUTER_MODELS_API}",
    "imported_at": "{IMPORT_DATE}",
    "model_count": {len(items)},
    "model_downloads": False,
    "live_provider_calls": False,
}}

OPENROUTER_MODEL_LINK_ITEMS = json.loads({payload!r})
'''
    OUTPUT_PATH.write_text(content, encoding="utf-8")


def main() -> int:
    models = fetch_models()
    items = [normalized_item(model) for model in models]
    ids = [item["canonical_id"] for item in items]
    if len(ids) != len(set(ids)):
        raise RuntimeError("duplicate generated OpenRouter canonical_id")
    write_module(items)
    print(f"source={OPENROUTER_MODELS_API}")
    print(f"model_count={len(items)}")
    print(f"output={OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
