// Read-only contract projections for a stateless frontend deployment. Runtime
// mutations are blocked unless their Agent API, LLM Gateway, or MCP Gateway
// boundary is reachable.

const tag = { live_backend: false, source: "frontend-projection" as const };
const AGENT_ROLES = ["planner", "coder", "tester", "devops"];
const AUTONOMOUS_LOGICAL_ROLES = ["supervisor", "planner", "explorer", "coder", "tester"] as const;
const AUTONOMOUS_ROLE_MAP: Record<(typeof AUTONOMOUS_LOGICAL_ROLES)[number], string> = {
  supervisor: "planner",
  planner: "planner",
  explorer: "planner",
  coder: "coder",
  tester: "tester",
};
const AUTONOMOUS_TEAM_NON_CLAIMS = [
  "Logical roles are overlays on the existing runtime pool, not separate worker binaries.",
  "An optional external runtime adapter may project read-only team presence without changing dispatch semantics.",
  "This status surface does not claim live provider execution, live MCP writes, or production deployment.",
  "Legacy four-role public contracts remain authoritative for the runtime pool itself.",
  "The read-only projection does not observe or mutate the internal task queue.",
];

type DefaultResult = {
  payload: Record<string, unknown>;
  status?: number;
};

function envNum(name: string, fallback: number): number {
  const v = Number(process.env[name]);
  return Number.isFinite(v) && v > 0 ? v : fallback;
}

export function projectedAuditEvents(): Array<Record<string, unknown>> {
  return [];
}

function authContract(): Record<string, unknown> {
  return {
    ...tag,
    contract_version: "auth-github-jwt-refresh-v1",
    contract: "auth_contract_visible",
    mode: "verified_identity_fail_closed",
    live_github_oauth_call: false,
    github_oauth_configured: false,
    jwt_signing_configured: false,
    credentials_configured: false,
    owner_activation_granted: false,
    owner_activation_required: true,
    credential_issuance_ready: false,
    missing_configuration: ["GITHUB_OAUTH_CLIENT_ID", "GITHUB_OAUTH_CLIENT_SECRET", "GITHUB_OAUTH_REDIRECT_URI", "GITHUB_OAUTH_OWNER_IDS", "JWT_SIGNING_SECRET_BASE64URL_256_BIT_MINIMUM"],
    activation_blockers: ["production_auth_identity_owner_grant"],
    access_token_ttl_seconds: 900,
    jwt: {
      algorithm: "HS256",
      access_token_ttl_seconds: 900,
      issuer: "cloud-superbrain-agent-api",
      audience: "cloud-superbrain-frontend",
      signing_secret_format: "base64url_256_bit_minimum",
      ephemeral_fallback: true,
    },
    oauth_state: {
      ttl_seconds: 600,
      one_time: true,
      server_store: "redis",
      cookie_name: "__Host-sb_oauth_state",
      cookie_same_site: "Lax",
      authorization_transport: "http_redirect_location",
      response_body_contains_state: false,
      scope: "read:user",
      state_format: "phase3-auth-state-<32_urlsafe_chars>",
    },
    refresh_token: {
      ttl_seconds: 604800,
      rotation_required: true,
      blacklist_store: "redis",
      active_registry_store: "redis",
      active_registry_required: true,
      body_token_allowed: false,
      signing_secret_required: true,
      complete_issuance_configuration_required: true,
    },
    cookie: { SameSite: "Strict", HttpOnly: true, Secure: true, host_prefix: true },
    cookie_flags: { SameSite: "Strict", HttpOnly: true, Secure: true, host_prefix: true },
    audit: { credential_issuance_requires_persistence: true, secret_material_allowed: false },
    endpoints: ["/api/v1/auth/github", "/api/v1/auth/callback", "/api/v1/auth/refresh", "/api/v1/auth/logout", "/api/v1/auth/me"],
    secret_output: false,
  };
}

function liveAgentRows(): Array<Record<string, unknown>> {
  return AGENT_ROLES.map((role) => ({
    agent_id: role,
    display_name: `${role[0].toUpperCase()}${role.slice(1)} Agent`,
    execution_role: role,
    has_session: false,
    previous_response_id: null,
    model: null,
  }));
}

function projectedTeamStatus(): Record<string, unknown> {
  const unavailableReason = "internal_queue_unavailable_at_read_boundary";
  return {
    ...tag,
    contract_version: "autonomous-coding-team-v1",
    dispatch_contract_version: "autonomous-task-dispatch-v1",
    team_mode: "logical_five_role_overlay_on_runtime_pool",
    runtime_source: "external_adapter",
    status: "external_degraded",
    dispatch_id: null,
    project_id: null,
    session_id: null,
    objective: "external runtime projection",
    trace_id: null,
    request_id: null,
    correlation_evidence_ref: null,
    audit_feed_evidence_ref: null,
    queue_depth: 0,
    queue_depth_by_priority: { high: 0, mid: 0, low: 0 },
    queue_depth_observed: false,
    logical_roles: [...AUTONOMOUS_LOGICAL_ROLES],
    logical_to_execution_map: { ...AUTONOMOUS_ROLE_MAP },
    external_runtime: {
      configured: false,
      provider: null,
      status: "unavailable",
      status_url: null,
      agents_url: null,
      ready: false,
      runtime: "cloud_native_read_only_projection",
      agents: [],
      logical_role_map: { ...AUTONOMOUS_ROLE_MAP },
      error: unavailableReason,
      live_provider_calls: false,
      direct_provider_calls: false,
      live_mcp_writes: false,
      provider_writes: false,
      production_deploy: false,
      production_rollout_claimed: false,
      secret_output: false,
    },
    runtime_pool_contract_version: "task-assignment-queue-contract-v1",
    write_scope: [],
    acceptance_criteria: [],
    constraints: [
      "Respect the fail-closed task policy before enqueue.",
      "Do not claim live provider calls, live MCP writes, or production deployment.",
      "Keep changes inside the declared write_scope.",
      "Escalate instead of bypassing blocked actions or human-review gates.",
    ],
    members: AUTONOMOUS_LOGICAL_ROLES.map((logicalRole) => ({
      logical_role: logicalRole,
      execution_agent_type: AUTONOMOUS_ROLE_MAP[logicalRole],
      task_id: null,
      latest_task_id: null,
      task_type: "external_runtime_projection",
      status: "unavailable",
      latest_status: "unavailable",
      priority: null,
      priority_level: null,
      priority_queue: null,
      allowed_tools: [],
      planned_capabilities: ["external_runtime_projection"],
      write_scope: [],
      acceptance_criteria: [],
      human_review_required: true,
      blocked_actions: [],
      current_status_source: "external_runtime",
      trace_id: null,
      request_id: null,
      correlation_evidence_ref: null,
      audit_feed_evidence_ref: null,
      latest_result: null,
      latest_error: unavailableReason,
    })),
    live_provider_calls: false,
    direct_provider_calls: false,
    live_mcp_writes: false,
    provider_writes: false,
    production_deploy: false,
    production_rollout_claimed: false,
    secret_output: false,
    non_claims: [...AUTONOMOUS_TEAM_NON_CLAIMS],
  };
}

const DEFAULTS: Record<string, () => Record<string, unknown>> = {
  "/api/v1/tasks/recent": () => ({
    ...tag,
    status: "degraded",
    runtime_available: false,
    reason: "stateful_runtime_not_configured",
    owner_precondition: "Fly runtime approval or a separately approved Neon/Upstash architecture expansion.",
    queue_depth: 0,
    queue_depth_by_priority: {},
    tasks: [],
  }),
  "/api/v1/task/dispatches/recent": () => ({
    ...tag,
    status: "degraded",
    runtime_available: false,
    reason: "stateful_runtime_not_configured",
    owner_precondition: "Fly runtime approval or a separately approved Neon/Upstash architecture expansion.",
    items: [],
  }),
  "/api/v1/sessions/recent": () => ({ ...tag, sessions: [] }),
  "/api/v1/audit/recent": () => ({ ...tag, events: projectedAuditEvents() }),
  "/api/v1/audit/mcp": () => ({ ...tag, events: [] }),
  "/api/v1/escalations/recent": () => ({ ...tag, escalations: [], events: [] }),
  "/api/v1/memory/consolidation/recent": () => ({ ...tag, events: [], summary: { total: 0 }, records: [], consolidations: [] }),
  "/api/v1/agents/status": () => ({
    ...tag,
    status: "degraded",
    runtime_available: false,
    reason: "stateful_runtime_not_configured",
    owner_precondition: "Fly runtime approval or a separately approved Neon/Upstash architecture expansion.",
    agents: [],
  }),
  "/api/v1/live-agents/status": () => ({
    ...tag,
    status: "degraded",
    contract_version: "live-agent-steering-v1",
    runtime_available: false,
    reason: "stateful_runtime_not_configured",
    owner_precondition: "Fly runtime approval or a separately approved Neon/Upstash architecture expansion.",
    runtime_source: null,
    agents: [],
    default_model: null,
  }),
  "/api/v1/team/status": projectedTeamStatus,
  "/api/v1/rate-limit/status": () => ({ ...tag, contract_version: "rate-limit-guard-v1", evidence_ref: "rate_limit_status_visible", status: "ok", limit: null, remaining: null, window_s: null }),
  "/api/v1/session-limits/status": () => ({ ...tag, contract_version: "session-llm-call-limit-v1", evidence_ref: "session_limit_status_visible", status: "ok", active_sessions: 0, max_sessions: null }),
  "/api/v1/budget": () => ({ ...tag, status: "ok", spent_usd: 0, max_usd: envNum("LIVE_LLM_MAX_BUDGET_USD", 20), live_provider_calls: false }),
  "/api/v1/costs": () => ({ ...tag, total_usd: 0, items: [] }),
  "/api/v1/costs/export": () => ({ ...tag, total_usd: 0, items: [], format: "json" }),
  "/api/v1/infra/budget": () => ({ ...tag, status: "ok", spent_eur: 0, cap_eur: 20 }),
  "/api/v1/auth/contract": authContract,
  "/api/v1/auth/github": () => ({
    ...authContract(),
    endpoint: "GET /api/v1/auth/github",
    status: "configuration_required",
    credentials_issued: false,
    state_required: true,
    state_issued: false,
    authorize_url: null,
  }),
  "/api/v1/auth/me": () => ({
    ...authContract(),
    status: "blocked",
    error: "auth_configuration_required",
    authenticated: false,
    identity_verified: false,
    token_returned: false,
    cookie_returned: false,
  }),
  "/api/v1/layer-interfaces/contract": () => ({
    ...tag,
    contract_version: "layer-interface-contracts-v1",
    evidence_ref: "layer_interface_contracts_visible",
    interfaces: [
      { id: "L1-L2", method: "POST", path: "/api/v1/orchestrator/dry-run", status: "verified" },
      { id: "L2-L5", method: "POST", path: "/api/v1/tools/read-only/execute", status: "verified" },
      { id: "L7-OBS", method: "GET", path: "/api/v1/audit/recent", status: "verified" },
    ],
  }),
  "/api/v1/clouds/render-offload/contract": () => ({
    ...tag,
    contract_version: "cloud-render-offload-surface-v1",
    evidence_ref: "cloud_render_offload_contract_runtime_visible",
    endpoint: "GET /api/v1/clouds/render-offload/contract",
    runtime_endpoint: "GET /api/v1/clouds/render-offload",
  }),
  "/api/v1/clouds/deployment-preflight/contract": () => ({
    ...tag,
    contract_version: "cloud-deployment-preflight-surface-v1",
    evidence_ref: "cloud_deployment_preflight_contract_runtime_visible",
    endpoint: "GET /api/v1/clouds/deployment-preflight/contract",
    runtime_endpoint: "GET /api/v1/clouds/deployment-preflight",
  }),
  "/api/v1/clouds/go-live-readiness/contract": () => ({
    ...tag,
    contract_version: "go-live-readiness-surface-v1",
    endpoint: "GET /api/v1/clouds/go-live-readiness/contract",
    runtime_endpoint: "GET /api/v1/clouds/go-live-readiness",
    runtime_contract_version: "go-live-readiness-v1",
    evidence_ref: "go_live_readiness_contract_runtime_visible",
    required_top_level_fields: [
      "contract_version",
      "status",
      "objective",
      "overall_percent",
      "completion_can_set_all_to_100",
      "workspace_page_count",
      "cloud_layer_total_count",
      "runtime_preflight_missing_or_blocked_gates",
      "external_audit_summary_status",
      "external_audit_missing_or_failed_gates",
      "external_audit_expected_missing_or_failed_gates",
      "external_audit_expected_status",
      "external_audit_expected_production_deploy_claim_allowed",
      "external_audit_summary_consistent",
      "external_audit_summary_consistency_errors",
      "external_audit_claims",
      "hard_blockers",
      "required_owner_inputs",
      "required_owner_scopes",
      "external_audit_required",
      "external_audit_summary_path",
      "owner_activation",
      "owner_sequence",
      "claim_policy",
      "policy_checks",
      "non_claims",
    ],
    expected_runtime_contract_version: "go-live-readiness-v1",
    supported_statuses: ["blocked_external_gates", "ready_for_owner_cloud_execution"],
    guarded_endpoints: [
      "GET /api/v1/project/progress/completion",
      "GET /api/v1/external-gates",
      "GET /api/v1/clouds/layers",
      "GET /api/v1/clouds/deployment-preflight",
      "GET /api/v1/workspace/wiring",
      "GET /api/v1/workspace/vertical-stack",
    ],
    required_verifiers: [
      "scripts/verify-go-live-readiness.ps1",
      "scripts/verify-external-gates.ps1",
      "scripts/verify-cloudflare-stateful-runtime.ps1",
      "scripts/verify-browser-contract.ps1",
    ],
    non_claims: [
      "No cloud resource was created, mutated, deployed, or deleted.",
      "No production deployment, release promotion, registry push, unrestricted provider access, or live MCP write is claimed.",
      "Localhost remains DEV-ONLY and cannot close hosted staging or production gates.",
      "This endpoint does not make the project 100 percent complete.",
    ],
  }),
  "/api/v1/system/fallback/contract": () => ({
    ...tag,
    contract_version: "system-unavailable-fallback-v1",
    contract_visible: "system_fallback_contract_visible",
    mode: "frontend_error_recovery_contract",
    ui_state: "System Unavailable",
    retry_action: "keep retry button visible",
  }),
  "/api/v1/memory/purge/contract": () => ({ ...tag, contract_version: "memory-dsgvo-purge-v1", endpoint: "GET /api/v1/memory/purge/jobs/{job_id}", evidence_ref: "memory_purge_job_status_visible" }),
  "/api/v1/memory/embedding-consistency/contract": () => ({
    ...tag,
    contract_version: "memory-embedding-consistency-v1",
    status: "verified",
    evidence_ref: "memory_embedding_consistency_contract_visible",
    audit_gap: "L-09",
    schema: { expected_columns: { embedding_model_version: "character varying(100)", content_embedding: "vector(1536)" } },
    current_embedding: { model_version: "text-embedding-3-small", dimensions: 1536, search_mode: "lexical_fallback" },
    frontend_memory_path: "none; stateful memory remains behind the Agent API PostgreSQL/pgvector boundary",
    direct_provider_calls: false,
    non_claims: ["No live embedding provider call or frontend persistence path is claimed."],
  }),
  "/api/v1/files/local/contract": () => ({
    ...tag,
    contract_version: "local-files-readonly-contract-v1",
    endpoint: "GET /api/v1/files/local/contract",
    host_filesystem_mounted: false,
    live_filesystem_reads: false,
    writes: false,
    secret_output: false,
  }),
  "/api/v1/models/capabilities/contract": () => ({
    ...tag,
    contract_version: "model-capabilities-contract-v1",
    runtime_endpoint: "GET /api/v1/models/capabilities",
    evidence_ref: "model_capabilities_contract_visible",
  }),
  "/api/v1/models/capabilities": () => ({
    ...tag,
    contract_version: "model-capabilities-contract-v1",
    routes: [
      { id: "llm_gateway", layer: "L4", status: "gateway_only" },
      { id: "marketplace", layer: "L5", status: "spec_only" },
      { id: "media", layer: "L4", status: "spec_only" },
      { id: "agents", layer: "L3", status: "spec_only" },
      { id: "observe", layer: "L7", status: "spec_only" },
    ],
    live_provider_calls: false,
  }),
  "/api/v1/costs/export/contract": () => ({ ...tag, contract_version: "cost-monitor-export-v1", supported_formats: ["csv"], evidence_ref: "cost_export_csv_generated" }),
  "/api/v1/rate-limit/contract": () => ({ ...tag, contract_version: "rate-limit-guard-v1", evidence_ref: "rate_limit_429_enforced" }),
  "/api/v1/session-limits/contract": () => ({ ...tag, contract_version: "session-llm-call-limit-v1", evidence_ref: "session_limit_429_enforced" }),
  "/api/v1/errors/contract": () => ({ ...tag, contract_version: "error-response-contract-v1", evidence_ref: "error_response_envelope_enforced" }),
  "/api/v1/security/headers/contract": () => ({
    ...tag,
    contract_version: "security-headers-v1",
    mode: "api_response_security_headers",
    enforced_by: "security_headers_middleware",
    applies_to: "all Agent API HTTP responses including error envelopes",
    headers: {
      "X-Content-Type-Options": "nosniff",
      "X-Frame-Options": "DENY",
      "Referrer-Policy": "no-referrer",
      "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
      "Content-Security-Policy": "default-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; report-uri /api/v1/security/csp/report",
      "Cross-Origin-Opener-Policy": "same-origin",
      "Cross-Origin-Resource-Policy": "same-origin",
      "X-Permitted-Cross-Domain-Policies": "none",
    },
    csp_report_contract: {
      contract_version: "csp-report-contract-v1",
      endpoint: "POST /api/v1/security/csp/report",
      evidence_ref: "csp_report_contract_visible",
      audit_evidence_ref: "csp_report_audit_persisted",
    },
    csrf_origin_contract: {
      contract_version: "csrf-origin-guard-v1",
      endpoint: "GET /api/v1/security/csrf/contract",
      evidence_ref: "csrf_origin_guard_visible",
      audit_evidence_ref: "csrf_origin_rejection_audited",
    },
    cross_origin_response_contract: {
      contract_version: "cross-origin-response-guard-v1",
      endpoint: "GET /api/v1/security/cross-origin/contract",
      evidence_ref: "cross_origin_response_guard_visible",
    },
    cors_policy: {
      mode: "same_origin_by_default",
      public_cross_origin_enabled: false,
    },
    evidence_ref: "security_headers_enforced",
    evidence_refs: {
      contract_visible: "security_headers_contract_visible",
      headers_enforced: "security_headers_enforced",
      same_origin_cors_policy: "security_headers_same_origin_policy",
      ui_visible: "security_headers_ui_visible",
      csp_report_visible: "csp_report_contract_visible",
      csrf_origin_guard_visible: "csrf_origin_guard_visible",
      cross_origin_response_guard_visible: "cross_origin_response_guard_visible",
    },
  }),
  "/api/v1/security/csp/contract": () => ({
    ...tag,
    contract_version: "csp-report-contract-v1",
    mode: "same_origin_redacted_audit_sink",
    endpoint: "POST /api/v1/security/csp/report",
    evidence_ref: "csp_report_contract_visible",
    audit_evidence_ref: "csp_report_audit_persisted",
    max_body_bytes: 16_384,
    accepted_content_types: ["application/csp-report", "application/json"],
    privacy: {
      uri_query_and_fragment_persisted: false,
      user_agent_persisted: false,
      cookies_or_credentials_persisted: false,
      raw_report_persisted: false,
    },
    live_external_report_forwarding: false,
    audit_persisted: false,
  }),
  "/api/v1/security/csrf/contract": () => ({
    ...tag,
    contract_version: "csrf-origin-guard-v1",
    mode: "fetch_metadata_and_same_origin_guard",
    endpoint: "GET /api/v1/security/csrf/contract",
    probe_endpoint: "POST /api/v1/security/csrf/probe",
    evidence_ref: "csrf_origin_guard_visible",
    audit_event_type: "security_csrf_request_rejected",
    audit_evidence_ref: "csrf_origin_rejection_audited",
    protected_methods: ["POST", "PUT", "PATCH", "DELETE"],
    protected_path_prefix: "/api/",
    safe_methods: ["GET", "HEAD", "OPTIONS", "TRACE"],
    rejection_status_code: 403,
    rejection_error: "csrf_origin_rejected",
    phase3_progress_after_proof: 42,
    rejection_reasons: ["fetch_metadata_cross_site", "invalid_or_null_origin", "origin_mismatch"],
    same_origin_browser_requests_allowed: true,
    non_browser_missing_metadata_allowed: true,
    cross_site_browser_requests_allowed: false,
    null_origin_allowed: false,
    raw_origin_persisted: false,
    cookie_or_authorization_value_persisted: false,
    live_external_forwarding: false,
  }),
  "/api/v1/security/cross-origin/contract": () => ({
    ...tag,
    contract_version: "cross-origin-response-guard-v1",
    mode: "same_origin_opener_and_resource_guard",
    endpoint: "GET /api/v1/security/cross-origin/contract",
    evidence_ref: "cross_origin_response_guard_visible",
    enforced_by: "security_headers_middleware",
    applies_to: "all Agent API HTTP responses including error envelopes",
    headers: {
      "Cross-Origin-Opener-Policy": "same-origin",
      "Cross-Origin-Resource-Policy": "same-origin",
      "X-Permitted-Cross-Domain-Policies": "none",
    },
    cors_policy: {
      public_cross_origin_enabled: false,
      attacker_origin_reflected: false,
      credentials_allowed_cross_origin: false,
    },
    phase3_progress_after_proof: 43,
    provider_write: false,
    live_mcp_write: false,
    state_write: false,
    production_deploy: false,
  }),
  "/api/v1/phase6/3d-camera-lighting/contract": () => ({
    ...tag,
    contract_version: "phase6-3d-camera-lighting-runtime-v1",
    mode: "phase6_lightweight_threejs_camera_lighting_runtime_contract",
    endpoint: "GET /api/v1/phase6/3d-camera-lighting/contract",
    evidence_ref: "phase6_3d_camera_lighting_runtime_visible",
    camera_lighting_strategy: "local_camera_rig_lighting_profile_state",
    camera_presets: ["wide", "close", "top"],
    lighting_profiles: ["studio", "night", "sunrise"],
    safe_fov_degrees: [38, 45, 58],
    safe_exposure_range: { min: 0.72, max: 1.18, step: 0.02 },
    local_camera_lighting_state_only_required: true,
    shader_hotload_allowed: false,
    external_asset_fetch_allowed: false,
    phase6_progress_after_proof: 40,
  }),
  "/api/v1/phase6/3d-gameplay-state/contract": () => ({
    ...tag,
    contract_version: "phase6-3d-gameplay-state-runtime-v1",
    mode: "phase6_lightweight_threejs_gameplay_state_runtime_contract",
    endpoint: "GET /api/v1/phase6/3d-gameplay-state/contract",
    evidence_ref: "phase6_3d_gameplay_state_runtime_visible",
    gameplay_state_strategy: "local_objective_score_checkpoint_state_machine",
    objectives: ["collect", "checkpoint", "survive"],
    score_increment: 10,
    checkpoint_increment: 1,
    loop_interval_ms: 1000,
    pause_safe_loop_required: true,
    local_gameplay_state_only_required: true,
    multiplayer_netcode_allowed: false,
    server_authoritative_sync_allowed: false,
    physics_engine_required: false,
    external_asset_fetch_allowed: false,
    network_calls_required: false,
    phase6_progress_after_proof: 48,
  }),
  "/api/v1/phase6/3d-asset-policy/contract": () => ({
    ...tag,
    contract_version: "phase6-3d-asset-policy-runtime-v1",
    mode: "phase6_lightweight_threejs_asset_policy_runtime_contract",
    endpoint: "GET /api/v1/phase6/3d-asset-policy/contract",
    evidence_ref: "phase6_3d_asset_policy_runtime_visible",
    asset_policy_strategy: "local_procedural_primitive_asset_catalog",
    asset_profiles: ["cube", "beacon", "ring"],
    material_variants: ["cyan", "amber", "rose"],
    asset_catalog_count: 3,
    material_variant_count: 3,
    remote_asset_count: 0,
    uploaded_asset_count: 0,
    procedural_primitives_only_required: true,
    local_asset_manifest_only_required: true,
    external_asset_fetch_allowed: false,
    binary_asset_upload_allowed: false,
    remote_cdn_allowed: false,
    asset_pipeline_service_started: false,
    network_calls_required: false,
    phase6_progress_after_proof: 56,
  }),
  "/api/v1/phase6/3d-save-load/contract": () => ({
    ...tag,
    contract_version: "phase6-3d-save-load-runtime-v1",
    mode: "phase6_volatile_browser_memory_scene_snapshot_contract",
    endpoint: "GET /api/v1/phase6/3d-save-load/contract",
    evidence_ref: "phase6_3d_save_load_runtime_visible",
    save_load_strategy: "typed_allowlisted_react_state_snapshot",
    snapshot_field_count: 15,
    snapshot_slots: 1,
    capture_required: true,
    restore_required: true,
    clear_required: true,
    load_disabled_without_snapshot_required: true,
    volatile_browser_memory_only_required: true,
    snapshot_discarded_on_reload_required: true,
    local_storage_allowed: false,
    indexeddb_allowed: false,
    cookie_persistence_allowed: false,
    service_worker_cache_allowed: false,
    cloud_save_sync_allowed: false,
    binary_snapshot_upload_allowed: false,
    server_snapshot_write_allowed: false,
    network_calls_required: false,
    phase6_progress_after_proof: 64,
  }),
  "/api/v1/phase6/3d-accessibility/contract": () => ({
    ...tag,
    contract_version: "phase6-3d-accessibility-runtime-v1",
    mode: "phase6_accessible_reduced_motion_2d_fallback_contract",
    endpoint: "GET /api/v1/phase6/3d-accessibility/contract",
    evidence_ref: "phase6_3d_accessibility_runtime_visible",
    accessibility_strategy: "system_aware_reduced_motion_semantic_keyboard_fallback",
    manual_reduced_motion_toggle_required: true,
    system_preference_detection_required: true,
    static_2d_fallback_required: true,
    semantic_region_required: true,
    keyboard_navigation_keys: ["ArrowDown", "ArrowRight", "ArrowUp", "ArrowLeft", "Home", "End", "Enter", "Space"],
    programmatic_scene_focus_required: true,
    global_focus_visible_required: true,
    aria_pressed_state_required: true,
    aria_controls_required: true,
    live_status_region_required: true,
    accessible_item_count: 10,
    browser_local_preference_only_required: true,
    speech_service_required: false,
    accessibility_telemetry_export_allowed: false,
    persistent_preference_write_allowed: false,
    network_calls_required: false,
    phase6_progress_after_proof: 72,
  }),
  "/api/v1/phase6/3d-netcode/contract": () => ({
    ...tag,
    contract_version: "phase6-3d-netcode-loopback-runtime-v1",
    mode: "phase6_two_peer_browser_loopback_lockstep_contract",
    endpoint: "GET /api/v1/phase6/3d-netcode/contract",
    evidence_ref: "phase6_3d_netcode_loopback_runtime_visible",
    netcode_strategy: "two_peer_manual_lockstep_browser_loopback",
    transport: "loopback",
    session_slots: 1,
    maximum_peers: 2,
    ready_barrier_required: true,
    manual_lockstep_required: true,
    packets_per_tick: 2,
    sequence_monotonic_required: true,
    disconnect_stops_simulation_required: true,
    threejs_remote_peer_marker_required: true,
    browser_memory_only_required: true,
    websocket_allowed: false,
    webrtc_allowed: false,
    matchmaking_allowed: false,
    public_lobby_allowed: false,
    server_authoritative_sync_allowed: false,
    network_calls_required: false,
    phase6_progress_after_proof: 80,
  }),
  "/api/v1/trace/contract": () => ({ ...tag, contract_version: "trace-id-propagation-v1", evidence_ref: "trace_id_header_roundtrip" }),
  "/api/v1/cache/contract": () => ({ ...tag, contract_version: "cache-control-no-store-v1", evidence_ref: "cache_control_headers_enforced" }),
  "/api/v1/request/contract": () => ({ ...tag, contract_version: "request-id-correlation-v1", evidence_ref: "request_id_audit_correlation" }),
  "/api/v1/agent-activity/contract": () => ({ ...tag, contract_version: "agent-activity-trace-v1", evidence_ref: "agent_activity_filtered_feed_visible" }),
  "/api/v1/agent-activity/recent": () => ({
    ...tag,
    contract_version: "agent-activity-trace-v1",
    mode: "stateless_frontend_projection",
    status: "degraded",
    events: [],
    audit_persisted: false,
  }),
  "/api/v1/tasks/assignment-contract": () => ({
    ...tag,
    contract_version: "task-assignment-queue-contract-v1",
    evidence_ref: "task_assignment_queue_contract_visible",
    audit_gap: "L-06",
    queue_key: "tasks:agent:queue",
    priority_queues: { high: "tasks:agent:queue:high", mid: "tasks:agent:queue:mid", low: "tasks:agent:queue:low" },
    priority_order: ["high", "mid", "low"],
    priority_policy: "high before mid before low",
    status_key_pattern: "task:status:{task_id}",
    recovery: "stale_queue_rescue",
  }),
  "/api/v1/agents/llm-streaming-contract": () => ({
    ...tag,
    contract_version: "agent-llm-streaming-contract-v1",
    evidence_ref: "agent_llm_streaming_contract_visible",
    audit_gap: "L-07",
    protocol: "openai_compatible_sse",
    done_frame: "data: [DONE]",
    parser: "parse_llm_gateway_sse_line",
    state_field: "stream_done_seen",
    non_claims: ["No live provider stream"],
  }),
  "/api/v1/live-agents/contract": () => ({
    ...tag,
    contract_version: "live-agent-steering-v1",
    mode: "openai_responses_via_llm_gateway",
    evidence_refs: { contract_visible: "live_agent_steering_contract_visible" },
    evidence_ref: "live_agent_steering_contract_visible",
    llm_gateway_endpoint: "POST /llm/v1/responses",
    llm_gateway_contract_version: "llm-responses-adapter-contract-v2",
    llm_gateway_contract_endpoint: "GET /llm/api/v1/responses/contract",
    required_llm_response_fields: ["output_text", "trace_id", "live_provider_calls", "model_downloads", "audit_persisted"],
    response_fields: ["trace_id", "continuity_reset", "live_provider_calls", "audit_persisted", "secret_output"],
    metadata_policy: {
      max_bytes: 8192,
      server_owned_keys: ["trace_id", "agent_type", "logical_agent_id", "project_id", "live_provider_calls_allowed", "gateway_path"],
      provider_authorization_from_request_body: false,
    },
    agents: liveAgentRows(),
  }),
  "/api/v1/phase2/runtime/contract": () => ({
    ...tag,
    contract_version: "phase2-runtime-v1",
    start_endpoint: "POST /api/v1/phase2/runtime/start",
    stream_endpoint: "POST /api/v1/orchestrator/dry-run/stream",
    runs_endpoint: "GET /api/v1/phase2/runtime/runs",
    sse_contract: "phase2-sse-event-contract-v1",
    evidence_refs: ["phase2_sse_event_contract_proof", "langgraph_mcp_timeout_controlled"],
    required_events: ["heartbeat", "agent_status", "error", "done"],
    live_provider_calls: false,
    checkpointing: "postgres",
  }),
  "/llm/api/v1/responses/contract": () => ({
    ...tag,
    contract_version: "llm-responses-adapter-contract-v2",
    evidence_ref: "llm_responses_adapter_contract_visible",
    runtime_endpoint: "POST /llm/v1/responses",
    service_runtime_route: "POST /v1/responses",
    adapter: {
      stream_passthrough: false,
      streaming_protocol: "openai-responses-sse-v1",
      stateful_sessions_supported: true,
      stateful_session_scope: "bounded_process_local_context_store",
    },
    request_schema: {
      stream: "boolean, default false; true emits deterministic Responses-native SSE",
      instructions: "optional string, maximum 8192 characters; prepended as system context",
      previous_response_id: "optional adapter response id for bounded process-local continuity",
      max_output_tokens: "optional integer from 1 through 8192",
    },
    streaming_schema: {
      protocol: "openai-responses-sse-v1",
      provider_passthrough: false,
      deterministic_only: true,
      limits: { output_tokens: 8192, instructions_chars: 8192, stored_contexts: 64, context_ttl_seconds: 1800 },
    },
    live_provider_calls: false,
    model_downloads: false,
    production_deploy: false,
    secret_output: false,
    negative_cases: [
      { request: { stream: "true" }, expected_status: 422, reason: "stream must remain a boolean" },
      {
        request: { stream: true, metadata: { live_provider_calls_allowed: true } },
        expected_status: 403,
        reason: "Responses streaming is deterministic-only and never activates a provider",
      },
      {
        request: { max_output_tokens: 8193 },
        expected_status: 422,
        reason: "requested output tokens must stay within the bounded adapter limit",
      },
      { request: { metadata: "not-an-object" }, expected_status: 422, reason: "metadata must stay structured for trace/audit policy" },
    ],
    failure_cases: [
      {
        condition: "stream audit persistence unavailable or rejected",
        expected_status: 503,
        terminal_event_emitted: false,
      },
      { condition: "previous_response_id unknown or expired", expected_status: 404 },
    ],
  }),
  "/mcp/api/v1/version-pinning/contract": () => ({
    ...tag,
    contract_version: "mcp-version-pinning-v1",
    evidence_ref: "mcp_version_pinning_contract_visible",
    audit_gap: "L-08",
    pins: ["fastapi==0.136.3", "uvicorn[standard]==0.49.0", "pydantic==2.13.4"],
    tool_contracts: [
      "github-branch-pr-plan-v1",
      "e2b-sandbox-lifecycle-v1",
      "filesystem-project-progress-read-v1",
    ],
    drift_policy: "exact == pinning",
    non_claims: ["No live MCP write"],
  }),
};

/** Returns a shape-correct honest 200 payload for a known endpoint, or null. */
export function knownDefault(pathname: string): Record<string, unknown> | null {
  const fn = DEFAULTS[pathname];
  return fn ? fn() : null;
}

export function projectedDefault(pathname: string, method: string): DefaultResult | null {
  if (method === "GET") {
    const exact = knownDefault(pathname);
    if (exact) return { payload: exact };
    const checkpoint = pathname.match(/^\/api\/v1\/orchestrator\/checkpoints\/([^/]+)$/);
    if (checkpoint) {
      return {
        status: 503,
        payload: {
          ...tag,
          contract_version: "phase2-runtime-v1",
          thread_id: checkpoint[1],
          status: "blocked",
          runtime_available: false,
          checkpointing: "unavailable_without_agent_api",
          state: null,
          accepted: false,
          audit_persisted: false,
        },
      };
    }
    const history = pathname.match(/^\/api\/v1\/sessions\/([^/]+)\/history$/);
    if (history) {
      return {
        status: 503,
        payload: {
          ...tag,
          contract_version: "session-history-v1",
          status: "blocked",
          runtime_available: false,
          requested_session_id: history[1],
          session: null,
          messages: [],
          tasks: [],
          audit_events: [],
          accepted: false,
          audit_persisted: false,
        },
      };
    }
  }
  if (method === "POST" && pathname === "/api/v1/phase2/runtime/start") {
    return {
      status: 503,
      payload: {
        ...tag,
        status: "blocked",
        contract_version: "phase2-runtime-v1",
        runtime_available: false,
        reason: "stateful_runtime_not_configured",
        owner_precondition: "Fly runtime approval or a separately approved Neon/Upstash architecture expansion.",
        run: null,
      },
    };
  }
  if (method === "GET" && pathname === "/api/v1/phase2/runtime/runs") {
    return {
      payload: {
        ...tag,
        status: "degraded",
        contract_version: "phase2-runtime-v1",
        evidence_ref: "phase2_runtime_run_status_visible",
        runtime_available: false,
        reason: "stateful_runtime_not_configured",
        owner_precondition: "Fly runtime approval or a separately approved Neon/Upstash architecture expansion.",
        runs: [],
      },
    };
  }
  if (method === "GET" && pathname === "/api/v1/auth/callback") {
    return {
      status: 503,
      payload: {
        ...authContract(),
        status: "blocked",
        error: "stateful_auth_boundary_unavailable",
        authenticated: false,
        accepted: false,
        audit_persisted: false,
      },
    };
  }
  if (method === "POST" && pathname === "/api/v1/auth/refresh") {
    return {
      status: 503,
      payload: {
        ...authContract(),
        status: "blocked",
        error: "stateful_auth_boundary_unavailable",
        refresh_token_rotated: false,
        old_refresh_token_blacklisted: false,
        accepted: false,
        audit_persisted: false,
      },
    };
  }
  if (method === "POST" && pathname === "/api/v1/auth/logout") {
    return {
      status: 503,
      payload: {
        ...authContract(),
        status: "blocked",
        error: "stateful_auth_boundary_unavailable",
        refresh_token_revoked: false,
        accepted: false,
        audit_persisted: false,
      },
    };
  }
  if (method !== "GET" && method !== "HEAD") {
    const requiredBoundary = pathname.startsWith("/llm/")
      ? "llm-gateway"
      : pathname.startsWith("/mcp/")
        ? "mcp-gateway"
        : "agent-api";
    return {
      status: 503,
      payload: {
        ...tag,
        contract_version: "frontend-provider-boundary-v1",
        status: "blocked",
        error: "configured_boundary_unavailable",
        endpoint: `${method} ${pathname}`,
        required_boundary: requiredBoundary,
        accepted: false,
        persisted: false,
        direct_provider_calls: false,
        live_provider_calls: false,
        live_mcp_writes: false,
        audit_persisted: false,
        secret_output: false,
      },
    };
  }
  return null;
}

/** Generic honest 200 envelope for any other surface with no live backend. */
export function genericDefault(pathname: string, method: string): Record<string, unknown> {
  return {
    ...tag,
    status: "ok",
    endpoint: `${method} ${pathname}`,
    items: [],
    data: null,
    note: "No live backend configured; this surface is answered by honest frontend projection (empty). Deterministic contracts/state are served as real data.",
  };
}

/** Real Prometheus-format frontend metrics (always 200, never fabricated). */
export function frontendMetrics(): string {
  const agentApi = process.env.AGENT_API_BASE_URL || process.env.AGENT_API_INTERNAL_URL ? 1 : 0;
  const llmGateway = process.env.LLM_GATEWAY_BASE_URL ? 1 : 0;
  const mcpGateway = process.env.MCP_GATEWAY_BASE_URL ? 1 : 0;
  return [
    "# HELP superbrain_frontend_up Frontend liveness (1=up).",
    "# TYPE superbrain_frontend_up gauge",
    "superbrain_frontend_up 1",
    "# HELP superbrain_agent_api_boundary_configured Agent API origin configured (1=yes).",
    "# TYPE superbrain_agent_api_boundary_configured gauge",
    `superbrain_agent_api_boundary_configured ${agentApi}`,
    "# HELP superbrain_llm_gateway_boundary_configured LLM Gateway origin configured (1=yes).",
    "# TYPE superbrain_llm_gateway_boundary_configured gauge",
    `superbrain_llm_gateway_boundary_configured ${llmGateway}`,
    "# HELP superbrain_mcp_gateway_boundary_configured MCP Gateway origin configured (1=yes).",
    "# TYPE superbrain_mcp_gateway_boundary_configured gauge",
    `superbrain_mcp_gateway_boundary_configured ${mcpGateway}`,
    "# HELP superbrain_frontend_direct_provider_calls Frontend direct provider calls (always 0).",
    "# TYPE superbrain_frontend_direct_provider_calls gauge",
    "superbrain_frontend_direct_provider_calls 0",
    "# HELP superbrain_client_3d_safe Client 3D runs with GPU-safety guards (1=yes).",
    "# TYPE superbrain_client_3d_safe gauge",
    "superbrain_client_3d_safe 1",
  ].join("\n") + "\n";
}
